version: '3.8'

services: 
 nginx:
  build:
   context: .
   dockerfile: nginx.dockerfile
  ports:
   - 81:80 
  volumes:
   - ./src:/var/www/html
  depends_on:
   - mysql
   - php
 mysql:
  image: mysql:5.7 
  ports:
    - 3308:3306
  environment:
   MYSQL_DATABASE: User_central
   MYSQL_USER: user
   MYSQL_PASSWORD: root
   MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./mysql:/var/lib/mysql 
 php:
  build:
   context: .
   dockerfile: php.dockerfile
  volumes:
    -  ./src:/var/www/html
  command: /bin/sh -c "chown -R laravel:laravel /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm -y /usr/local/etc/php-fpm.conf -R"
  
 composer:
  build:
   context: .
   dockerfile: composer.dockerfile
  volumes:
    - ./src:/var/www/html
  working_dir: /var/www/html  

 phpMyAdmin:
  image: phpmyadmin/phpmyadmin
  links:
      - mysql
  ports:
      - "8000:80"
  environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    


   


     
      